### ISSUE TITLE
Bestbuy code problem

### ISSUE THREAD

**Issue by 21796114** [KyleAbent/ps5preorderscript#1]
When I run the code, I get the following error:

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project bestbuyorder: Compilation failure
com/mycompany/bestbuyorder/doTest.java:[190,39] variable e is already defined in method doIt()
-> [Help 1]

I need help.

**Comment by KyleAbent** [comment]
No you don't
